# Indice de DataFrames utilizados

In [1]:
#|echo: false
import pandas as pd

## Análisis de producto terminado de una fabricación diaria de camembert

En formato `CSV` y `Excel`

In [2]:
#|echo: false


df = pd.read_csv("datos/camembert.csv", decimal = ",", sep=';', encoding="ISO-8859-1")
df.head()

        fecha  fabricacion    est    mg    ph  cloruros  coliformes
0  11/01/2020            1  46.68  24.0  4.85      1.50        80.0
1  12/01/2020            1  48.09  25.0  4.67      1.61         0.0
2  13/01/2020            1  45.97  24.0  4.71      1.48      9200.0
3  14/01/2020            1  46.24  23.5  4.78      1.69        20.0
4  15/01/2020            1  45.81  23.0  4.77      1.56       150.0

## Datos de fabricación de diferentes recetas de queso ibérico para balance de materia

In [3]:
#|echo: false

df = pd.read_csv("datos/fab_queso_sim.csv", decimal = ",", sep=';', encoding="ISO-8859-1")
df.head()

,fecha,entrada_kg,entrada_litros,entrada_grasa_g_l,entrada_prot_g_l,cuba_fab_litros,cuba_fab_grasa_g_l,cuba_fab_prot_g_l,stock_cierre_litros,queso_kg,queso_est_pct,queso_mg_pct
0,31/12/2023,4895.0,4752.0,45.13,36.68,NaN,NaN,NaN,4752.0,NaN,NaN,NaN
1,01/01/2024,5516.0,5355.0,40.98,34.63,5025.0,41.07,33.95,5107.0,637.56,49.95,25.46
2,02/01/2024,4938.0,4794.0,40.88,35.16,5029.0,39.99,33.61,4901.0,630.34,51.68,26.12
3,03/01/2024,5704.0,5538.0,43.38,35.32,5032.0,40.55,33.85,5439.0,628.81,51.29,26.16
4,04/01/2024,5170.0,5019.0,41.47,35.93,5035.0,39.90,33.78,5458.0,656.69,49.81,25.28

## Lecturas de humedad relativa y temperatura en una cueva para maduración de queso

In [4]:
#|echo: false

df = pd.read_csv("datos/control_cueva_queso.csv", decimal = ",", sep=';', encoding="ISO-8859-1")
df.head()

                 fecha       temp       hrel
0  2020-01-01 00:00:00  10.232205  87.796974
1  2020-01-01 00:05:00  10.091809  87.807218
2  2020-01-01 00:10:00  10.139651  87.801365
3  2020-01-01 00:15:00  10.030622  87.796916
4  2020-01-01 00:20:00   9.901193  87.811986

## Datos de análisis de quesos tipo ibérico a la salida de la salmuera

In [5]:
#|echo: false

df_fab_queso = pd.read_csv("datos/datos_laboratorio.csv", decimal = ",", sep=';', encoding="ISO-8859-1")
df_fab_queso.head()

,fecha,receta,formato,maduracion,extractoseco,materiagrasa,sal,ph
0,07/10/2012,mezcla 5,3 kg,tierno,57.330002,32.139999,1.04,5.27
1,07/10/2012,mezcla 5,500 g,tierno,58.549999,32.980000,0.99,5.45
2,07/10/2012,mezcla 5,3 kg,tierno,58.509998,33.160000,1.16,5.26
3,07/10/2012,mezcla 5,500 g,tierno,59.009998,33.070000,1.27,5.46
4,07/10/2012,mezcla 5,500 g,tierno,57.869999,31.940001,0.93,5.47

## Datos de un proceso de envasado de queso en unidades de 250 g

In [6]:
#|echo: false

df_fab_queso = pd.read_csv("datos/peso.csv", decimal = ",", sep=';', encoding="ISO-8859-1")
df_fab_queso.head()

                 fecha    peso
0  2020-05-16 09:00:00  254.55
1  2020-05-16 09:00:10  246.92
2  2020-05-16 09:00:20  236.29
3  2020-05-16 09:00:30  241.60
4  2020-05-16 09:00:40  247.41

## Datos de entrada de leche en una fábrica de queso ibérico de mezcla.

In [7]:
#|echo: false

df_fab_queso = pd.read_csv("datos/rutas_leche.csv", decimal = ",", sep=';', encoding="ISO-8859-1")
df_fab_queso.head()

,fecha,cod_ruta,tipo_leche,peso,temp,acidez,ph,densidad,est,mg,prot,lactosa,caseina
0,04/11/2015,13,VACA,13380,6.0,15.0,6.84,1.030,12.45,3.71,3.34,4.71,2.31
1,04/11/2015,13,VACA,8520,6.0,15.0,6.81,1.030,12.83,3.94,3.40,4.74,2.41
2,04/11/2015,22,VACA,23900,6.0,15.0,6.82,1.030,12.47,3.66,3.22,4.85,2.29
3,04/11/2015,41,CABRA,4180,6.1,14.0,6.86,1.032,14.88,5.50,3.95,4.70,2.88
4,04/11/2015,24,VACA,14640,7.7,15.0,6.86,1.030,12.35,3.68,3.25,4.69,2.26