# Indice de DataFrames utilizados

In [1]:
#|echo: false
import pandas as pd

## Análisis de producto terminado de una fabricación diaria de camembert

En formato `CSV` y `Excel`

In [2]:
#|echo: false

df = pd.read_csv("datos/camembert.csv", decimal = ",", sep=';', encoding="ISO-8859-1")
df.head()

        fecha  fabricacion    est    mg    ph  cloruros  coliformes
0  11/01/2020            1  46.68  24.0  4.85      1.50        80.0
1  12/01/2020            1  48.09  25.0  4.67      1.61         0.0
2  13/01/2020            1  45.97  24.0  4.71      1.48      9200.0
3  14/01/2020            1  46.24  23.5  4.78      1.69        20.0
4  15/01/2020            1  45.81  23.0  4.77      1.56       150.0

## Datos de fabricación de diferentes recetas de queso ibérico para balance de materia

In [3]:
#|echo: false

df = pd.read_csv("datos/fab_queso_bm_limpio.csv", decimal = ",", sep=';', encoding="ISO-8859-1")
df.head()

,fecha,receta,litros_past,kg_cuba,est_cuba,mg_cuba,mp_cuba,lactosa_cuba,ph_final_moldeo_cuba,formato,est_salida_salmuera,mg_salida_salmuera,ph_salida_salmuera,peso_queso_total,sal_queso
0,23/02/2022,light,12330,12860.510,10.28,2.46,3.38,4.44,6.46,3 kg,50.85,20.34,5.44,1419.3,1.47
1,24/02/2022,mezcla,7500,7704.462,12.80,4.90,3.89,4.01,6.35,barra,59.42,32.13,5.40,1062.4,1.31
2,01/03/2022,light,13030,13867.370,10.41,2.47,3.43,4.51,6.40,barra,52.10,21.15,5.34,1536.0,1.17
3,22/04/2022,vaca,13910,14382.290,12.76,4.97,3.93,3.86,NaN,barra,54.13,29.34,5.46,2228.0,1.59
4,04/03/2022,oveja,11890,12344.190,14.37,5.86,4.55,3.96,6.42,barra,57.60,31.99,5.42,2051.0,NaN

## Lecturas de humedad relativa y temperatura en una cueva para maduración de queso

In [4]:
#|echo: false

df = pd.read_csv("datos/control_cueva_queso.csv", decimal = ",", sep=';', encoding="ISO-8859-1")
df.head()

                 fecha       temp       hrel
0  2020-01-01 00:00:00  10.232205  87.796974
1  2020-01-01 00:05:00  10.091809  87.807218
2  2020-01-01 00:10:00  10.139651  87.801365
3  2020-01-01 00:15:00  10.030622  87.796916
4  2020-01-01 00:20:00   9.901193  87.811986

## Datos de análisis de quesos tipo ibérico a la salida de la salmuera

In [5]:
#|echo: false

df_fab_queso = pd.read_csv("datos/datos_laboratorio.csv", decimal = ",", sep=';', encoding="ISO-8859-1")
df_fab_queso.head()

,fecha,receta,formato,maduracion,extractoseco,materiagrasa,sal,ph
0,07/10/2012,mezcla 5,3 kg,tierno,57.330002,32.139999,1.04,5.27
1,07/10/2012,mezcla 5,500 g,tierno,58.549999,32.980000,0.99,5.45
2,07/10/2012,mezcla 5,3 kg,tierno,58.509998,33.160000,1.16,5.26
3,07/10/2012,mezcla 5,500 g,tierno,59.009998,33.070000,1.27,5.46
4,07/10/2012,mezcla 5,500 g,tierno,57.869999,31.940001,0.93,5.47

## Datos a salida de saladero de quesos ibéricos

In [6]:
#|echo: false

df_fab_queso = pd.read_csv("datos/datos_quesos.csv", decimal = ",", sep=';', encoding="ISO-8859-1")
df_fab_queso.head()

        Fecha  Num_Cuba   Lote       FORMATO    PH     ES     MG   SAL
0  05/11/2015         7  42015    Barra 3 kg  5.51  58.31  32.36  1.45
1  13/03/2015        28  18315  Barra 4,2 kg  5.49  58.59  30.90  1.18
2  04/05/2016         8  23616    Barra 3 kg  5.43  57.82  31.60  1.57
3  14/03/2016         9  18516    Barra 3 kg  5.59  58.17  31.24  1.37
4  23/05/2016         6  25516          1 kg  5.46  59.71  31.92  0.92

## Datos de un proceso de envasado de queso en unidades de 250 g

In [7]:
#|echo: false

df_fab_queso = pd.read_csv("datos/peso.csv", decimal = ",", sep=';', encoding="ISO-8859-1")
df_fab_queso.head()

                 fecha    peso
0  2020-05-16 09:00:00  254.55
1  2020-05-16 09:00:10  246.92
2  2020-05-16 09:00:20  236.29
3  2020-05-16 09:00:30  241.60
4  2020-05-16 09:00:40  247.41

## Datos de entrada de leche en una fábrica de queso ibérico de mezcla.

In [8]:
#|echo: false

df_fab_queso = pd.read_csv("datos/rutas_leche.csv", decimal = ",", sep=';', encoding="ISO-8859-1")
df_fab_queso.head()

,codruta,peso,tipoleche,fecha,acidez,caseina,densidad,est,lactosa,mg,ph,prot,temp
0,13,13380,VACA,04/11/2015,15.0,2.31,1.030,12.45,4.71,3.71,6.84,3.34,6.0
1,13,8520,VACA,04/11/2015,15.0,2.41,1.030,12.83,4.74,3.94,6.81,3.40,6.0
2,22,23900,VACA,04/11/2015,15.0,2.29,1.030,12.47,4.85,3.66,6.82,3.22,6.0
3,41,4180,CABRA,04/11/2015,14.0,2.88,1.032,14.88,4.70,5.50,6.86,3.95,6.1
4,24,14640,VACA,04/11/2015,15.0,2.26,1.030,12.35,4.69,3.68,6.86,3.25,7.7

## Datos de análisis de producto terminado de diferentes productos, en una tabla Excel

In [9]:
#|echo: false
# Read the Excel file and specify the sheet name
df = pd.read_excel('datos/analisis.xlsx', sheet_name='analisis')
df.head()

,FECHA,CLAVE,CODIGO,HUMEDAD,EXSECO,ESMAGRO,HQMAGRO,GRASA,GRASASECO,PH,CLORUROS,COLIS,fecha_2
0,7,660,10078,48.48,51.52,18.52,72.36,33.0,64.05,5.17,1.53,160,1988-01-07
1,7,660,20078,47.35,52.65,17.65,72.85,35.0,66.48,5.21,1.25,10,1988-01-07
2,7,660,30078,47.02,52.98,19.98,70.18,33.0,62.29,5.28,1.34,20,1988-01-07
3,8,660,10088,47.02,52.98,18.98,71.24,34.0,64.18,5.16,1.34,18620,1988-01-08
4,8,660,20088,47.22,52.78,18.78,71.55,34.0,64.42,5.25,1.34,2200,1988-01-08